name: Run Python Unit Tests on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: |
          cd laboratories/cicd-documentation
          python3 main.py
